#Server Country Flags properties file
#Wed May 27 12:24:36 GMT-03:00 2026
borderColor=(65, 65, 65, 255)
displayCooldownFlag=true
displayUnknownFlag=true
flagBorder=true
flagPosition=behindName
forceEnglish=false
mapButton=true
mapButtonRight=true
reloadOnRefresh=false
resolveRedirects=true
showDistance=true
showDistrict=false
showHomeOnMap=false
showISP=false
useKm=true
